/*USUÁRIOS*/
CREATE TABLE USUARIO (
    COD_USUARIO SERIAL PRIMARY KEY,
    DES_USUARIO VARCHAR(100),
    DES_EMAIL VARCHAR(4000),
    DES_SENHA VARCHAR(4000),
    IND_ATIVO TINYINT(1) NOT NULL CHECK (IND_ATIVO IN (0, 1))
);

/*USUÁRIO MASTER COM LOGIN: ADMIN E SENHA:123456*/
INSERT INTO USUARIO(DES_USUARIO, DES_EMAIL, DES_SENHA, IND_ATIVO) VALUES('ADMIN', 'admin@admin.com', '$2a$10$/.UlDdUzaEsO75pUvMuqX.2wfq0OthzunbqPVb6rvtd0z/HYCfPWa', 1);
COMMIT;

/*INGREDIENTES*/
CREATE TABLE INGREDIENTE (
	COD_INGREDIENTE SERIAL PRIMARY KEY,
    DES_INGREDIENTE VARCHAR(500) NOT NULL,
    NUM_LOTE VARCHAR(100) NOT NULL,
    DTA_VALIDADE DATE NOT NULL,
    COD_EAN VARCHAR(20),
    IND_ATIVO TINYINT(1) NOT NULL CHECK (IND_ATIVO IN (0, 1))
);

/*RECEITAS*/
CREATE TABLE RECEITA (
	COD_RECEITA SERIAL PRIMARY KEY,
    DES_RECEITA VARCHAR(500) NOT NULL,
    DTH_INCLUSAO TIMESTAMP NOT NULL,
    COD_USUARIO_INCLUSAO BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (COD_USUARIO_INCLUSAO) REFERENCES USUARIO(COD_USUARIO)
);

/*INGREDIENTES DAS RECEITAS*/
CREATE TABLE RECEITA_INGREDIENTE(
    NUM_SEQ SERIAL PRIMARY KEY,
    COD_RECEITA BIGINT UNSIGNED NOT NULL,
    COD_INGREDIENTE BIGINT UNSIGNED NOT NULL,
	NUM_ORDEM INT NOT NULL,
    QTD_KGS DECIMAL(12, 4),
    DTH_INCLUSAO TIMESTAMP NOT NULL,
    COD_USUARIO_INCLUSAO BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (COD_RECEITA) REFERENCES RECEITA(COD_RECEITA),
    FOREIGN KEY (COD_INGREDIENTE) REFERENCES INGREDIENTE(COD_INGREDIENTE),
    FOREIGN KEY (COD_USUARIO_INCLUSAO) REFERENCES USUARIO(COD_USUARIO)
);
